config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/join/complete' => 'welcome#complete'
  get '/join' => 'members#new', as: :join
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  patch '/chores/:id/complete' => 'chores#complete', as: :complete_chore
  delete '/chores/clear' => 'chores#destroy', as: :clear_chores
  get '/households/join' => 'households#join', as: :join_household_modal
  post '/households/join' => 'households#join_household', as: :join_household
  patch '/bills/:id/pay' => 'bills#pay', as: :pay_household_bill

  resources :households, except: [:index] do
    get '/calendar/day' => 'calendar#day'
    get '/calendar/load' => 'calendar#load'
    get 'control' => 'households#control'
    resources :members, except: [:show]
    get '/members/reload' => 'members#reload'
    resources :rooms, except: [:index]
    get '/room_items/reload' => 'room_items#reload'
    resources :bills, except: [:index]
    get '/chores/reload' => 'chores#reload'
    resources :chores, except: [:index]
    resources :list_items, only: [:destroy]
    get '/list_items/reload' => 'list_items#reload'
    resources :room_items, except: [:index]
  end

  resources :members, only: [:create]
  resources :members, only: [:show] do
    get '/chores/reload' => 'chores#reload'
    get '/messages/inbox' => 'messages#inbox', as: :inbox
    get '/messages/check' => 'messages#check', as: :check_messages
    post '/messages/reply' => 'messages#reply'
    resources :messages, except: [:index, :update]
    get '/list_items/reload' => 'list_items#reload'
    resources :list_items, except: [:index]
    patch 'request/room_item/:id' => 'room_items#inventory_request', as: :room_item_request
    get '/room_items/reload' => 'room_items#reload'
  end
end

app/models/chore.rb
class Chore < ActiveRecord::Base
  include Shared

  belongs_to :member

  validates :task, presence: true
  validates :member_id, presence: true
  validates :due_date, presence: true
  validate :future

  default_scope { order(due_date: :desc) }
  scope :over_due, -> { where("due_date < ?", Date.today) }
  scope :due_today, -> { where(due_date: Date.today) }
  scope :due_tomorrow, -> { where(due_date: Date.today + 1) }
  scope :future, -> { where("due_date > ?", Date.today + 1) }
  scope :completed, -> { where(completed: true) }
  scope :for, -> (household) {
    joins(:member).
    where(members: {household_id: household.id})
  }

  def self.scopes
    {
      over_due: "Over Due",
      due_today: "Today",
      due_tomorrow: "Tomorrow",
      future: "Future",
      completed: "Completed"
    }
  end

  def cols
    [:member_id, :due_date, :task]
  end

  def future
    if !due_date.blank? && due_date <= Date.today
      errors.add(:due_date, "can't be in the past.")
    end
  end

  def scopes
    Chore.scopes.select do |scope, scope_title|
      Chore.send(scope).pluck(:id).include?(self.id)
    end
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  include Shared

  has_secure_password

  validates_presence_of :first_name, :last_name, :email
  validates_uniqueness_of :email
  validate :positive_income
  validate :household_auth

  belongs_to :household
  has_many :chores, dependent: :destroy
  has_one :room, dependent: :destroy
  has_one :list, dependent: :destroy
  has_many :recieved_messages, class_name: 'Message', primary_key: 'id', foreign_key: 'recipient_id', dependent: :destroy
  has_many :sent_messages, class_name: 'Message', primary_key: 'id', foreign_key: 'sender_id', dependent: :destroy

  after_create :assign_list_and_room

  def assign_list_and_room
    if self.household
      create_list(name: self.name)
      create_room(name: self.name, household_id: self.household.id)
    end
  end

  def join_household(household)
    if !household.members.empty?
      self.head_of_household = false
    end
    self.household = household
    self.save
    self.assign_list_and_room
  end

  def self.scopes
    {member.name.downcase.to_sym => member.name}
  end

  def self.find_or_create_by_oauth(auth_hash)
    name = auth_hash[:name].split(" ")
    self.where(email:auth_hash["email"]).first_or_create do |member|
      member.first_name = name.first
      member.last_name = name.last
      member.password = SecureRandom.hex
      member.household_id = 0
      member.head_of_household = true
    end
  end

  def cols
    [:first_name, :last_name, :monthly_income, :email, :password]
  end

  def name
    first_name
  end

  def positive_income
    if monthly_income == nil || monthly_income < 0
      errors.add(:monthly_income, "cannot be below zero.")
    end
  end

  def household_auth
    if !head_of_household && household_id == nil
      errors.add(:base, "Household ID/passphrase don't match our records.")
    end
  end

  def first_head?
    self == self.household.members.first
  end
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_chore, only:[:edit, :update, :destroy, :complete]
  before_action :redirect_unless_logged_in

  def new
    @chore = Chore.new
    respond_to do |format|
      format.js {
        render 'shared/new_edit',
        locals:{obj:@chore}
      }
    end
  end

  def create
    @chore = Chore.new(chore_params)
    respond_to do |format|
      if @chore.save
        format.js
      else
        format.js {
          render 'shared/errors',
          locals:{obj:@chore}
        }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js {
        render 'shared/new_edit',
        locals:{obj:@chore}
      }
    end
  end

  def update
    @old_scopes = @chore.scopes.dup
    respond_to do |format|
      if @chore.update(chore_params)
        format.js
      else
        format.js {
          render "shared/errors",
          locals:{obj:@chore}
        }
      end
    end
  end

  def destroy
    respond_to do |format|
      locals = {objs:Chore.for(current_household)}
      if @chore
        locals[:obj] = @chore
        @chore.destroy
        format.js {
          render 'shared/delete',
          locals:locals
        }
      else
        @chores = locals[:objs].completed
        locals[:chore_ids] = @chores.pluck(:id)
        @chores.delete_all
        format.js {
          render 'destroy',
          locals:locals
        }
      end
    end
  end

  def complete
    @old_scopes = @chore.scopes.dup
    @chore.toggle!(:completed)
    respond_to do |format|
      format.js
    end
  end

  def reload
    if current_url.include?("household")
      @chores = Chore.for(current_household)
    else
      @chores = current_member.chores
    end
    respond_to do |format|
      format.js
    end
  end

  private
    def set_chore
      @chore = Chore.find_by(id: params[:id])
    end

    def chore_params
      params.require(:chore).permit(:task, :due_date, :member_id)
    end
end

app/helpers/chores_helper.rb
module ChoresHelper
  def strikeout(chore)
    'strike-through' if chore.completed
  end

  def chores_hash(scope, scope_title, chores)
    hash = {scope:scope, scope_title:scope_title, chores:[]}
    chores.empty? ? hash : hash.merge({chores:chores})
  end
end

app/views/chores/_admin_chore_card.html.erb
<span class="card-title">
  <u class='lg-font'>
    Chores
  </u>
  <span class='pb-2'>
    <%= add_btn(:chore, current_household) %>
    <%= refresh_btn(current_household, :chores) %>
  </span>
</span>

<div id="accordion-chore" data-children=".chore-item">
  <% Chore.scopes.each do |scope, scope_title| %>
    <%= content_tag :div,
          class:'chore_item',
          id:"#{scope.to_s}_chores_collapse" do %>
      <%= render 'chores/chores',
            {scope_title: scope_title,
             scope: scope,
             chores: @chores.send(scope)} %>
    <% end %>
  <% end %>
</div>

app/views/chores/_all.html.erb
<div id="#Accordion_<%= scope.to_s %>" data-children=".item">
  <div class="item">
    <span class="badge badge-default">
      <%= chores.send(scope).count %>
    </span>
    <a  class='btn btn-sm' data-toggle="collapse" data-parent="#Accordion_<%= scope.to_s %>" href="#<%= scope.to_s %>" aria-expanded="true" aria-controls="<%= scope.to_s %>">
      <%= scope_title %>
    </a>
    <div id="<%= scope.to_s %>" class="collapse" role="tabpanel">
      <% if scope_title == "Completed" %>
      <div class="row">
      <div class="col-1">
      </div>
      <div class="col-11">
        <%= link_to "Clear Completed", clear_chores_path,
        method: :delete,
        data:{confirm: "Clear all completed chores?" },
        class:'btn btn-sm',
        params:{scope:scope}
          %>
      </div>
    </div>
      <% end %>
      <div class="row">
        <div class="col">
        </div>
        <div class="col-11">
          <table class='table table-sm table-hover'>
            <thead>
              <tr>
                <% if household_partial? %>
                  <th scope='col-8'>Task</th>
                  <th scope='col-2'>Member</th>
                  <th scope='col-2'>Due</th>
                <% else %>
                  <th scope='col-10'>Task</th>
                  <th scope='col-2'>Due</th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <%= render chores.send(scope) %>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/chores/_chore.html.erb
<% if admin? %>
  <td>
    <%= remove_btn(current_household, chore) %>
  </td>
  <td>
    <span title='Edit'>
      <%= link_to chore.task,
            edit_household_chore_path(current_household, chore),
            remote:true,
            class:"btn btn-sm text-info #{strikeout(chore)}" %>
    </span>
  </td>
  <%= content_tag :td,
        class:strikeout(chore) do %>
    <%= chore.member.name %>
  <% end %>
<% else %>
  <td>
    <span title='Complete'>
      <%= link_to chore.task,
            complete_chore_path(chore),
            class:"btn btn-sm text-info complete_chore_#{chore.id} #{strikeout(chore)}",
            method:'patch',
            remote:true %>
    </span>
  </td>
<% end %>
<%= content_tag :td,
      class:strikeout(chore) do %>
  <%= formatted_due_date(chore.due_date) %>
<% end %>

app/views/chores/_chores.html.erb
<%= content_tag :span,
      class:badge_color(scope),
      id:badge_id(scope, "chores") do %>
  <%= chores.count %>
<% end %>
<%= accordion_link("#{scope.to_s}_chores", "chore") {scope_title} %>
<div id="<%= scope.to_s %>_chores" class="collapse" role="tabpanel">
  <% if scope_title == "Completed" && admin? %>
    <div class="row pt-2">
      <div class="col-1">
      </div>
      <div class="col-11">
        <%= link_to "Clear Completed", clear_chores_path,
              method: :delete,
              data:{confirm:"<div class='text-center h5 pt-3'>Clear all completed chores?</div>"},
              class:btn,
              remote:true %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-1">
    </div>
    <div class="col-11">
      <table class='table table-sm table-hover'>
        <thead>
          <tr>
            <% if admin? %>
              <th class='tbl-col-1'></th>
              <th class='tbl-col-7'>Task</th>
              <th class='tbl-col-2'>Member</th>
              <th class='tbl-col-2'>Due</th>
            <% else %>
              <th class='tbl-col-9'>Task</th>
              <th class='tbl-col-3'>Due</th>
            <% end %>
          </tr>
        </thead>
        <%= content_tag :tbody,
              id:tbody_id(scope, "chores") do %>
          <%= render partial:'chores/chores_tr',
                collection:chores,
                as: :chore,
                locals:{scope:scope} %>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/chores/_chores_tr.html.erb
<%= content_tag :tr,
      class:chore.row_id do %>
  <%= render 'chores/chore',
        chore:chore,
        scope:scope %>
<% end %>

app/views/chores/_form.html.erb
<div class='form-group row'>
  <div class="col-4 text-center">
    <%= f.label :member_id,
          class:'col-form-label' %>
  </div>
  <div class='col-8'>
    <%= f.collection_select(:member_id,
          current_household.members,
          :id,
          :first_name,
          {prompt:'Select Member'},
          {class:'custom-select form-control-sm'}) %>
  </div>
</div>

<div class='form-group form-inline row'>
  <div class="col-4">
    <%= f.label :due_date,
          'Due',
          class:'text-center col-form-label' %>
  </div>
  <div class='col-8'>
    <%= content_tag :div,
          id:"chore_due_date" do %>
      <%= f.date_select :due_date,
            { use_two_digit_numbers:true,
              start_year:Date.today.year,
              end_year:Date.today.year + 1,
              order: [:month, :day, :year],
              prompt:{
                year:'Yr',
                month:'Mo',
                day:'Day'
              }
            },
              {class:'form-control form-control-sm'} %>
    <% end %>
  </div>
</div>

<div class='form-group row text-center'>
  <div class="col-4">
    <%= f.label :task,
          class:'col-form-label' %>
  </div>
  <div class='col-8'>
    <%= f.text_area :task,
     placeholder: "Task",
     class:'form-control form-control-sm' %>
  </div>
</div>

app/views/chores/_member_chore_card.html.erb
<span class='card-title'>
  <u class='lg-font'>
    Chores
  </u>
  <span class="pb-2">
    <%= refresh_btn(current_member, :chores) %>
  </span>
</span>

<div id="accordion-chore" data-children=".chore-item">
  <% Chore.scopes.each do |scope, scope_title| %>
    <%= content_tag :div,
          class:'chore_item',
          id:"#{scope.to_s}_chores_collapse" do %>
      <%= render 'chores/chores',
            {scope_title: scope_title,
             scope: scope,
             chores: @chores.send(scope)} %>
    <% end %>
  <% end %>
</div>

app/views/chores/complete.js.erb
$(".<%= @chore.row_id %>").remove();

<% @old_scopes.each do |scope, scope_title| %>
  $("#<%= badge_id(scope, @chore) %>")
      .html("<%= current_member.chores.send(scope).count %>");
<% end %>

<% @chore.scopes.each do |scope, scope_title| %>
  $("#<%= badge_id(scope, @chore) %>")
      .html("<%= current_member.chores.send(scope).count %>");
  $("#<%= tbody_id(scope, @chore) %>")
      .append("<tr class='<%= @chore.row_id %>'></tr>");
<% end %>

$(".<%= @chore.row_id %>")
    .html("<%= j render "chores/chore", chore:@chore %>");

<% if @chore.completed %>
  $(".complete_<%= @chore.row_id %>").addClass("strike");
<% else %>
  $(".complete_<%= @chore.row_id %>").removeClass("strike");
<% end %>

app/views/chores/create.js.erb
$('#dialog').modal('toggle');
<% @chore.scopes.each do |scope, scope_title| %>
  $("#<%= badge_id(scope, @chore) %>")
      .html("<%= Chore.send(scope).count %>");
  $("#<%= tbody_id(scope, @chore) %>")
      .prepend("<tr class='<%= @chore.row_id %>'></tr>");
  $(".<%= @chore.row_id %>")
      .html("<%= j render "chores/chore", chore:@chore %>");
<% end %>

app/views/chores/delete.js.erb
<% chore_ids.each do |id| %>
  $(".chore_<%= id %>").remove();
<% end %>
<% obj.class.scopes.keys.each do |scope| %>
  $("#<%= "#{scope.to_s}_chores_badge" %>").html("<%= objs.send(scope).count %>");
<% end %>

app/views/chores/destroy.js.erb
<% chore_ids.each do |id| %>
  $(".chore_<%= id %>").remove();
<% end %>
<% Chore.scopes.keys.each do |scope| %>
  $("#<%= badge_id(scope, "chores") %>")
      .html("<%= objs.send(scope).count %>");
<% end %>

app/views/chores/reload.js.erb
<% Chore.scopes.each do |scope, scope_title| %>
  $("#<%= scope.to_s %>_chores_collapse")
      .html("<%= j render "chores/chores", chores_hash(scope, scope_title, @chores.send(scope)) %>");
<% end %>

app/views/chores/update.js.erb
$('#dialog').modal('toggle');

<% if @old_scopes != @chore.scopes %>
  $(".<%= @chore.row_id %>").remove();
  <% @old_scopes.each do |scope, scope_title| %>
    $("#<%= badge_id(scope, @chore) %>")
        .html("<%= Chore.for(current_household).send(scope).count %>");
  <% end %>

  <% @chore.scopes.each do |scope, scope_title| %>
    $("#<%= badge_id(scope, @chore) %>")
        .html("<%= Chore.for(current_household).send(scope).count %>");
    $("#<%= tbody_id(scope, @chore) %>")
        .append("<tr class='<%= @chore.row_id %>'></tr>");
  <% end %>
<% end %>
$(".<%= @chore.row_id %>")
    .html("<%= j render "chores/chore", chore:@chore %>");