config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/join/complete' => 'welcome#complete'
  get '/join' => 'members#new', as: :join
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  patch '/chores/:id/complete' => 'chores#complete', as: :complete_chore
  delete '/chores/clear' => 'chores#destroy', as: :clear_chores
  get '/households/join' => 'households#join', as: :join_household_modal
  post '/households/join' => 'households#join_household', as: :join_household
  patch '/bills/:id/pay' => 'bills#pay', as: :pay_household_bill

  resources :households, except: [:index] do
    get '/calendar/day' => 'calendar#day'
    get '/calendar/load' => 'calendar#load'
    get 'control' => 'households#control'
    resources :members, except: [:show]
    get '/members/reload' => 'members#reload'
    resources :rooms, except: [:index]
    get '/room_items/reload' => 'room_items#reload'
    resources :bills, except: [:index]
    get '/chores/reload' => 'chores#reload'
    resources :chores, except: [:index]
    resources :list_items, only: [:destroy]
    get '/list_items/reload' => 'list_items#reload'
    resources :room_items, except: [:index]
  end

  resources :members, only: [:create]
  resources :members, only: [:show] do
    get '/chores/reload' => 'chores#reload'
    get '/messages/inbox' => 'messages#inbox', as: :inbox
    get '/messages/check' => 'messages#check', as: :check_messages
    post '/messages/reply' => 'messages#reply'
    resources :messages, except: [:index, :update]
    get '/list_items/reload' => 'list_items#reload'
    resources :list_items, except: [:index]
    patch 'request/room_item/:id' => 'room_items#inventory_request', as: :room_item_request
    get '/room_items/reload' => 'room_items#reload'
  end
end

app/models/household.rb
class Household < ActiveRecord::Base
  include Shared

  has_secure_password

  has_many :members, dependent: :destroy
  has_many :bills, dependent: :destroy
  has_many :rooms, dependent: :destroy

  validates :name, :city, :state, :zip_code, presence: true
  validates :address1, presence: true, uniqueness: true

  def cols
    [:name, :address1, :city, :state, :zip_code, :password]
  end
end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  before_action :redirect_unless_logged_in, except: [:new, :create]
  before_action :set_household, only: [:control, :edit, :update, :destroy]

  def control
    @chores = Chore.for(current_household)
    @chores_by_date = @chores.group_by(&:due_date)
    @lists = List.for(current_household)
    @items = Item.all.pluck(:name)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @bills = current_household.bills.group_by(&:due_date)
    @events = @bills.merge(@chores_by_date) {|k, v1, v2| [*v1, *v2]}
    session[:admin] = true
  end

  def join
    respond_to do |format|
      format.js
    end
  end

  def join_household
    household = Household.find_by(id:params[:household_id])
    respond_to do |format|
      if household && household.authenticate(params[:household_passphrase])
        current_member.join_household(household)
        format.js {
          render 'create'
        }
      else
        format.js {
          render 'join_errors'
        }
      end
    end
  end

  def new
    @household = Household.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @household = Household.new(household_params)
    respond_to do |format|
      if @household.save
        current_member.join_household(@household)
        format.js
      else
        format.js {
          render 'shared/errors',
          locals: {obj:@household}
        }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js {
        render 'shared/new_edit',
        locals:{obj:@household}
      }
    end
  end

  def update
    respond_to do |format|
      if @household.update(household_params)
        format.js
      else
        format.js {
          render 'shared/errors',
          locals: {obj:@household}
        }
      end
    end
  end

  def destroy
    @household.destroy
    redirect_to root_path
  end

  private
    def set_household
      @household ||= current_household
    end

    def household_params
      params.require(:household).permit(:name, :address1, :address2, :city, :state, :zip_code, :password)
    end
end

app/helpers/households_helper.rb
module HouseholdsHelper
  def household_destroy_btn
    content_tag :small do
      link_to "Remove Household",
        [current_household],
        method:'delete',
        class:'text-danger small justify-right',
        data:{
          confirm:"<div class='text-center h5 pt-3'>This action will remove your household account and all of its members from our database.<br>Continue?</div>",
          commit:"Delete Household",
          cancel:"Cancel"
        }
    end
  end

  def household_income
    number_to_currency(current_household.members.pluck(:monthly_income).sum)
  end
end

app/views/households/_admin_household_card.html.erb
<span class="card-title">
  <u class='lg-font'>
    Household
  </u>
  <span class='pb-2'>
    <%= link_to "Edit",
          edit_household_path(current_household),
          remote:true,
          class:btn %>
    <%= menu_link("household", "Rooms") %>
    <small class='text-muted small pl-2'>
      Monthly Income: <strong><%= household_income %></strong>
    </small>
  </span>
</span>

<div class='room-tab pb-2'>
  <div class="collapse border border-left-0 border-right-0" id='rooms'>
    <div id='reload_rooms' class="card-block p-3">
      <%= render 'rooms/rooms' %>
    </div>
  </div>
</div>
<div class='d-inline text-muted pl-3'>
  ID#: <%= current_household.id %>
</div>
<%= content_tag :div,
      id:'edit_household' do %>
  <%= render 'households/household',
        household:current_household %>
<% end %>
<%= household_destroy_btn %>

app/views/households/_content.html.erb
<%= content_for :header do %>
  <%= @household.new_record? ? "Create Household" : "Edit Household" %>
<% end %>

<%= content_for :body_footer do %>
<div class="modal-body">
  <div class="mr-4">
    <%= form_for @household,
          remote:true do |f| %>
      <%= render "households/form", f:f %>
    </div>
  </div>

  <div class="modal-footer">
    <%= content_tag :div,
          id:"household_errors",
          class:errors do %>
    <% end %>
    <%= content_tag :div,
          id:"member_errors",
          class:errors do %>
    <% end %>
      <%= f.submit "Create",
            class:btn,
            form:"new_household" %>
    <% end %>
  </div>
<% end %>

app/views/households/_form.html.erb
<div class='form-group row text-center'>
  <div class="col-4">
    <%= f.label :name,
          "Name",
          class:"col-form-label" %>
  </div>
  <div class='col-8'>
    <%= f.text_field :name,
          placeholder: "Name",
          class:'form-control form-control-sm' %>
  </div>
</div>

<div class="form-group row text-center">
  <div class="col-4">
    <%= f.label :address1,
          "Address 1",
          class:"col-form-label" %>
  </div>
  <div class="col-8">
    <%= f.text_field :address1,
          placeholder: "Address 1",
          class:'form-control form-control-sm' %>
  </div>
</div>

<div class="form-group row text-center">
  <div class="col-4">
    <%= f.label :address2,
          "Address 2",
          class:"col-form-label" %>
  </div>
  <div class="col-8">
    <%= f.text_field :address2,
          placeholder: "Address 2",
          class:'form-control form-control-sm' %>
  </div>
</div>

<div class="form-group row text-center">
  <div class="col-4">
    <%= f.label :city,
          "City",
          class:"col-form-label" %>
  </div>
  <div class="col-8">
    <%= f.text_field :city,
          placeholder: "City",
          class:'form-control form-control-sm' %>
  </div>
</div>

<div class="form-group row text-center">
  <div class="col-4">
    <%= f.label :state,
          "State",
          class:"col-form-label" %>
  </div>
  <div class="col-8">
    <%= f.text_field :state,
          placeholder: "State",
          class:'form-control form-control-sm' %>
  </div>
</div>

<div class="form-group row text-center">
  <div class="col-4">
    <%= f.label :zip_code,
        "Zip Code",
        class:"col-form-label" %>
  </div>
  <div class="col-8">
    <%= f.number_field :zip_code,
          placeholder: "Zip Code",
          class:'form-control form-control-sm' %>
  </div>
</div>

<div class="form-group row text-center">
  <div class="col-4">
    <%= f.label :password,
          "Password",
          class:"col-form-label" %>
  </div>
  <div class="col-8">
    <%= f.password_field :password,
          placeholder:"Password",
          class:'form-control form-control-sm',
          aria:{describedby:"passwordHelpBlock"} %>
    <small id='passwordHelpBlock' class='form-text text-muted'>
      <% if f.object.persisted? %>
        Leave password field blank unless changing password.
      <% else %>
        This password will be used to invite new members to your household.
      <% end %>
    </small>
  </div>
</div>

app/views/households/_household.html.erb
<div class="row">
  <div class="col-1">
  </div>
  <div class="col-9">
    <div class="row">
      <div class="<%= label_size %> text-right pl-3">
        <p class='font-weight-bold'>Name:</p>
      </div>
      <div class="<%= field_size %> text-left">
        <%= household.name %>
      </div>
    </div>
    <div class="row">
      <div class="<%= label_size %> text-right pl-3">
        <p class='font-weight-bold'>Address1:</p>
      </div>
      <div class="<%= field_size %> text-left">
        <%= household.address1 %>
      </div>
    </div>
    <div class="row">
      <div class="<%= label_size %> text-right pl-3">
        <p class='font-weight-bold'>Address2:</p>
      </div>
      <div class="<%= field_size %> text-left">
        <%= household.address2 %>
      </div>
    </div>
    <div class="row">
      <div class="<%= label_size %> text-right pl-3">
        <p class='font-weight-bold'>City:</p>
      </div>
      <div class="<%= field_size %> text-left">
        <%= household.city %>
      </div>
    </div>
    <div class="row">
      <div class="<%= label_size %> text-right pl-3">
        <p class='font-weight-bold'>State:</p>
      </div>
      <div class="<%= field_size %> text-left">
        <%= household.state %>
      </div>
    </div>
    <div class="row">
      <div class="<%= label_size %> text-right pl-3">
        <p class='font-weight-bold'>Zip Code:</p>
      </div>
      <div class="<%= field_size %> text-left">
        <%= household.zip_code %>
      </div>
    </div>
    <br>
  </div>  
</div>

app/views/households/_join_content.html.erb
<%= content_for :header do %>
  Join Household
<% end %>

<%= content_for :body_footer do %>
  <div class="modal-body">
    <div class="mr-4">
      <%= form_tag join_household_path,
            id:"join_household",
            method:'post',
            remote:true do %>
        <div class="form-group row text-center">
          <div class="col-4">
            <%= label_tag 'household_id',
                  'Household ID',
                  class:"col-form-label" %>
          </div>
          <div class="col-8">
            <%= number_field_tag :household_id,
                  nil,
                  class:'form-control form-control-sm' %>
          </div>
        </div>
        <div class="form-group row text-center">
          <div class="col-4">
            <%= label_tag 'household_passphrase',
                  'Passphrase',
                  class:'text-center col-form-label' %>
          </div>
          <div class="col-8">
            <%= text_field_tag :household_passphrase,
                  nil,
                  class:'form-control form-control-sm' %>
          </div>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%= content_tag :div,
            id:"join_household_errors",
            class:errors do %>
      <% end %>
        <%= submit_tag "Join",
              form:"join_household",
              class:btn %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/households/control.html.erb
<div id='admin-control' data-children='.link'>
  <div class='text-center'>
    <% menu_links = %w(Calendar Chores Bills Requests Inventory Members Household) %>
    <% menu_links.each do |link| %>
      <%= menu_link("admin-control", link) %>
    <% end %>
  </div>
  <br>
  <% menu_collapse = {
        calendar:"calendar",
        chores:"chore",
        bills:"bill",
        requests:"list_item",
        inventory:"room_item",
        members:"member",
        household:"household"
    } %>
  <% menu_collapse.each do |key, value| %>
    <%= link_div(key, value) %>
  <% end %>
</div>

app/views/households/create.js.erb
$('#dialog').modal('toggle');
window.location = "<%= member_path(current_member) %>";

app/views/households/join.js.erb
$("#modal-info").html("<%= j render 'join_content', household:@household %>");
$("#modal-dialog").html("<%= j render 'shared/dialog' %>");
$("#dialog").modal("toggle");

app/views/households/join_errors.js.erb
$("#join_household_errors")
    .html("<small class='d-block'>The provided email/password combination does not match our records.</small>");

app/views/households/new.js.erb
$("#modal-info").html("<%= j render 'content', household:@household %>");
$("#modal-dialog").html("<%= j render 'shared/dialog' %>");
$("#dialog").modal("toggle");

app/views/households/update.js.erb
$('#dialog').modal('toggle');
$("#edit_household")
    .html("<%= j render 'households/household', household:@household%>");
$("#household_name")
    .html("<%= current_household.name %>")